version: '3.8'

services:
  # Flask应用
  app:
    build: .
    container_name: etermaiweb-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DATABASE_URL=postgresql://postgres:Postgre,.1@172.17.0.1:5432/etermaiweb
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    networks:
      - etermaiweb-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s



  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: etermaiweb-redis
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - etermaiweb-network

volumes:
  redis_data:

networks:
  etermaiweb-network:
    driver: bridge 